[server]
port = 8000
address = "0.0.0.0"
enableWebsocketCompression = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
